spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5435/task_db
    username: postgres
    password: postgres
    hikari:
      schema: task_app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_app_schema
      connection-timeout: 10000
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  jwt:
    secret: "secretKey"
    tokenExpiration: 30m
    refreshTokenExpiration: 30m
