version: '3'
services:
  postgres:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_db
    container_name: task_container
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

#docker
#сменить порт 5435 если требуется
#docker compose up
